// Mock data para NONINO EMPANADAS

export const stores = [
  {
    id: 'store-1',
    name: 'Nonino Empanadas - Centro',
    address: 'Av. San Martín 123, Centro',
    phone: '+54 11 1234-5678',
    coordinates: { lat: -34.6037, lng: -58.3816 },
    zone: 'centro',
    hours: {
      monday: { open: '11:00', close: '23:00' },
      tuesday: { open: '11:00', close: '23:00' },
      wednesday: { open: '11:00', close: '23:00' },
      thursday: { open: '11:00', close: '23:00' },
      friday: { open: '11:00', close: '24:00' },
      saturday: { open: '11:00', close: '24:00' },
      sunday: { open: '12:00', close: '22:00' },
    },
    isOpen: true,
    rating: 4.8,
    deliveryTime: '30-45 min',
    minOrder: 2000,
  },
  {
    id: 'store-2',
    name: 'Nonino Empanadas - Norte',
    address: 'Calle Belgrano 456, Zona Norte',
    phone: '+54 11 8765-4321',
    coordinates: { lat: -34.5847, lng: -58.3943 },
    zone: 'norte',
    hours: {
      monday: { open: '11:00', close: '23:00' },
      tuesday: { open: '11:00', close: '23:00' },
      wednesday: { open: '11:00', close: '23:00' },
      thursday: { open: '11:00', close: '23:00' },
      friday: { open: '11:00', close: '24:00' },
      saturday: { open: '11:00', close: '24:00' },
      sunday: { open: '12:00', close: '22:00' },
    },
    isOpen: true,
    rating: 4.7,
    deliveryTime: '35-50 min',
    minOrder: 2500,
  },
];

export const categories = [
  {
    id: 'tradicionales',
    name: 'Tradicionales',
    description: 'Nuestras empanadas clásicas de toda la vida',
    image: '/api/placeholder/300/200',
    icon: '🥟',
  },
  {
    id: 'gourmet',
    name: 'Gourmet',
    description: 'Sabores únicos y sofisticados',
    image: '/api/placeholder/300/200',
    icon: '✨',
  },
  {
    id: 'vegetarianas',
    name: 'Vegetarianas',
    description: 'Opciones deliciosas sin carne',
    image: '/api/placeholder/300/200',
    icon: '🥬',
  },
  {
    id: 'dulces',
    name: 'Dulces',
    description: 'Para los amantes de lo dulce',
    image: '/api/placeholder/300/200',
    icon: '🍯',
  },
];

export const products = [
  // Tradicionales
  {
    id: 'emp-001',
    sku: 'EMP-CARNE-001',
    name: 'Empanada de Carne',
    description: 'Carne picada, cebolla, huevo duro, aceitunas y condimentos',
    price: 450,
    category: 'tradicionales',
    image: '/api/placeholder/400/300',
    isAvailable: true,
    preparationTime: 15,
    ingredients: ['carne picada', 'cebolla', 'huevo', 'aceitunas', 'condimentos'],
    allergens: ['gluten', 'huevo'],
    rating: 4.8,
    reviews: 156,
    isPopular: true,
    nutritionalInfo: {
      calories: 320,
      protein: 18,
      carbs: 28,
      fat: 15,
    },
  },
  {
    id: 'emp-002',
    sku: 'EMP-POLLO-002',
    name: 'Empanada de Pollo',
    description: 'Pollo desmenuzado, verduras y especias',
    price: 420,
    category: 'tradicionales',
    image: '/api/placeholder/400/300',
    isAvailable: true,
    preparationTime: 15,
    ingredients: ['pollo', 'cebolla', 'pimiento', 'condimentos'],
    allergens: ['gluten'],
    rating: 4.7,
    reviews: 123,
    isPopular: true,
    nutritionalInfo: {
      calories: 290,
      protein: 22,
      carbs: 25,
      fat: 12,
    },
  },
  {
    id: 'emp-003',
    sku: 'EMP-JYQUE-003',
    name: 'Empanada de Jamón y Queso',
    description: 'Jamón cocido y queso mozzarella',
    price: 380,
    category: 'tradicionales',
    image: '/api/placeholder/400/300',
    isAvailable: true,
    preparationTime: 12,
    ingredients: ['jamón', 'queso mozzarella'],
    allergens: ['gluten', 'lactosa'],
    rating: 4.6,
    reviews: 89,
    nutritionalInfo: {
      calories: 310,
      protein: 16,
      carbs: 24,
      fat: 16,
    },
  },

  // Gourmet
  {
    id: 'emp-004',
    name: 'Empanada de Cordero',
    description: 'Cordero patagónico con hierbas finas',
    price: 650,
    category: 'gourmet',
    image: '/api/placeholder/400/300',
    isAvailable: true,
    preparationTime: 18,
    ingredients: ['cordero', 'romero', 'tomillo', 'cebolla morada'],
    allergens: ['gluten'],
    rating: 4.9,
    reviews: 67,
    isPopular: true,
    nutritionalInfo: {
      calories: 380,
      protein: 24,
      carbs: 26,
      fat: 19,
    },
  },
  {
    id: 'emp-005',
    name: 'Empanada de Salmón',
    description: 'Salmón rosado, queso crema y eneldo',
    price: 720,
    category: 'gourmet',
    image: '/api/placeholder/400/300',
    isAvailable: true,
    preparationTime: 16,
    ingredients: ['salmón', 'queso crema', 'eneldo', 'cebollín'],
    allergens: ['gluten', 'lactosa', 'pescado'],
    rating: 4.8,
    reviews: 43,
    nutritionalInfo: {
      calories: 340,
      protein: 20,
      carbs: 22,
      fat: 18,
    },
  },

  // Vegetarianas
  {
    id: 'emp-006',
    name: 'Empanada de Verduras',
    description: 'Mix de verduras de estación con queso',
    price: 380,
    category: 'vegetarianas',
    image: '/api/placeholder/400/300',
    isAvailable: true,
    preparationTime: 14,
    ingredients: ['calabaza', 'espinaca', 'queso', 'cebolla'],
    allergens: ['gluten', 'lactosa'],
    rating: 4.5,
    reviews: 78,
    nutritionalInfo: {
      calories: 270,
      protein: 12,
      carbs: 32,
      fat: 10,
    },
  },
  {
    id: 'emp-007',
    name: 'Empanada Caprese',
    description: 'Tomate, mozzarella y albahaca fresca',
    price: 420,
    category: 'vegetarianas',
    image: '/api/placeholder/400/300',
    isAvailable: true,
    preparationTime: 12,
    ingredients: ['tomate', 'mozzarella', 'albahaca'],
    allergens: ['gluten', 'lactosa'],
    rating: 4.7,
    reviews: 56,
    isPopular: true,
    nutritionalInfo: {
      calories: 290,
      protein: 14,
      carbs: 28,
      fat: 13,
    },
  },

  // Dulces
  {
    id: 'emp-008',
    name: 'Empanada de Dulce de Leche',
    description: 'Dulce de leche artesanal argentino',
    price: 350,
    category: 'dulces',
    image: '/api/placeholder/400/300',
    isAvailable: true,
    preparationTime: 10,
    ingredients: ['dulce de leche'],
    allergens: ['gluten', 'lactosa'],
    rating: 4.9,
    reviews: 134,
    isPopular: true,
    nutritionalInfo: {
      calories: 280,
      protein: 6,
      carbs: 38,
      fat: 12,
    },
  },
  {
    id: 'emp-009',
    name: 'Empanada de Membrillo y Queso',
    description: 'Dulce de membrillo con queso cremoso',
    price: 380,
    category: 'dulces',
    image: '/api/placeholder/400/300',
    isAvailable: true,
    preparationTime: 12,
    ingredients: ['dulce de membrillo', 'queso cremoso'],
    allergens: ['gluten', 'lactosa'],
    rating: 4.6,
    reviews: 45,
    nutritionalInfo: {
      calories: 300,
      protein: 8,
      carbs: 42,
      fat: 11,
    },
  },
];

export const promotions = [
  {
    id: 'promo-001',
    title: 'Docena Mixta',
    description: '12 empanadas surtidas con 15% de descuento',
    discount: 15,
    type: 'percentage',
    minQuantity: 12,
    validUntil: '2024-12-31',
    image: '/api/placeholder/500/300',
    isActive: true,
    conditions: 'Válido para empanadas tradicionales y vegetarianas',
  },
  {
    id: 'promo-002',
    title: 'Combo Familiar',
    description: '6 empanadas + bebida grande',
    discount: 20,
    type: 'combo',
    originalPrice: 3200,
    salePrice: 2560,
    validUntil: '2024-11-30',
    image: '/api/placeholder/500/300',
    isActive: true,
    includes: ['6 empanadas a elección', 'Bebida 1.5L'],
  },
  {
    id: 'promo-003',
    title: 'Martes de Gourmet',
    description: 'Todas las empanadas gourmet con 25% OFF',
    discount: 25,
    type: 'category',
    category: 'gourmet',
    dayOfWeek: 2, // Martes
    validUntil: '2024-12-31',
    image: '/api/placeholder/500/300',
    isActive: true,
  },
];

export const deliveryZones = [
  {
    id: 'centro',
    name: 'Centro',
    deliveryFee: 0,
    estimatedTime: '30-40 min',
    minOrder: 2000,
    isAvailable: true,
  },
  {
    id: 'norte',
    name: 'Zona Norte',
    deliveryFee: 500,
    estimatedTime: '35-50 min',
    minOrder: 2500,
    isAvailable: true,
  },
  {
    id: 'sur',
    name: 'Zona Sur',
    deliveryFee: 600,
    estimatedTime: '40-55 min',
    minOrder: 2500,
    isAvailable: true,
  },
  {
    id: 'este',
    name: 'Zona Este',
    deliveryFee: 700,
    estimatedTime: '45-60 min',
    minOrder: 3000,
    isAvailable: true,
  },
  {
    id: 'oeste',
    name: 'Zona Oeste',
    deliveryFee: 550,
    estimatedTime: '35-50 min',
    minOrder: 2500,
    isAvailable: true,
  },
];

export const orderStatuses = {
  pending: { label: 'Pendiente', color: 'yellow', description: 'Esperando confirmación' },
  confirmed: { label: 'Confirmado', color: 'blue', description: 'Pedido confirmado, preparando' },
  preparing: { label: 'Preparando', color: 'orange', description: 'Cocinando tus empanadas' },
  ready: { label: 'Listo', color: 'green', description: 'Listo para entrega/retiro' },
  inDelivery: { label: 'En camino', color: 'purple', description: 'En camino a tu dirección' },
  delivered: { label: 'Entregado', color: 'green', description: 'Pedido entregado' },
  cancelled: { label: 'Cancelado', color: 'red', description: 'Pedido cancelado' },
};

export const mockOrders = [
  {
    id: 'EMP-2024-001',
    customerId: 'user-1',
    items: [
      { ...products[0], quantity: 6 },
      { ...products[1], quantity: 4 },
    ],
    status: 'preparing',
    total: 4380,
    createdAt: '2024-01-15T14:30:00Z',
    estimatedDelivery: '15:15',
    deliveryAddress: 'Av. Corrientes 1234, CABA',
    store: stores[0],
  },
  {
    id: 'EMP-2024-002',
    customerId: 'user-1',
    items: [
      { ...products[3], quantity: 3 },
      { ...products[7], quantity: 3 },
    ],
    status: 'delivered',
    total: 3000,
    createdAt: '2024-01-10T19:45:00Z',
    deliveredAt: '2024-01-10T20:30:00Z',
    deliveryAddress: 'Calle Florida 567, CABA',
    store: stores[1],
    rating: 5,
    review: 'Excelente calidad, llegaron calentitas!',
  },
];

export const adminMetrics = {
  totalSales: 125000,
  totalOrders: 450,
  totalCustomers: 1230,
  averageOrderValue: 2780,
  topProducts: [
    { product: products[0], sales: 890 },
    { product: products[1], sales: 756 },
    { product: products[7], sales: 634 },
  ],
  salesByDay: [
    { day: 'Lun', sales: 15000 },
    { day: 'Mar', sales: 18000 },
    { day: 'Mie', sales: 22000 },
    { day: 'Jue', sales: 25000 },
    { day: 'Vie', sales: 32000 },
    { day: 'Sab', sales: 35000 },
    { day: 'Dom', sales: 28000 },
  ],
  recentOrders: mockOrders,
};
